<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  26055 => 'ZAMTEL',
  26056 => 'MTN',
  26057 => 'Airtel',
  26058 => 'Beeline Telecoms',
  26075 => 'ZAMTEL',
  26076 => 'MTN',
  26077 => 'Airtel',
  26078 => 'Beeline Telecoms',
  26095 => 'ZAMTEL',
  26096 => 'MTN',
  26097 => 'Airtel',
  26098 => 'Beeline Telecoms',
);
