<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  3620 => 'Yettel Hungary',
  3630 => 'Magyar Telekom',
  36312000 => 'Netfone Telecom',
  36312001 => 'Netfone Telecom',
  3631310 => 'One',
  3631311 => 'One',
  3631312 => 'One',
  3631313 => 'One',
  3631314 => 'One',
  3631315 => 'One',
  3631316 => 'One',
  3631317 => 'One',
  3631318 => 'One',
  36313190 => 'One',
  36313191 => 'One',
  36313192 => 'One',
  36313193 => 'One',
  36313194 => 'One',
  36313195 => 'One',
  36313196 => 'One',
  36313197 => 'One',
  36313199 => 'One',
  3631320 => 'One',
  3631321 => 'One',
  3631322 => 'One',
  3631323 => 'One',
  3631324 => 'One',
  3631325 => 'One',
  3631326 => 'One',
  3631327 => 'One',
  3631328 => 'One',
  36313290 => 'One',
  36313291 => 'One',
  36313292 => 'One',
  3631330 => 'One',
  3631331 => 'One',
  3631332 => 'One',
  36313330 => 'Vidanet',
  36313331 => 'Vidanet',
  36313666 => 'One',
  36317000 => 'TARR',
  36317001 => 'TARR',
  36317002 => 'TARR',
  36317003 => 'TARR',
  36317004 => 'TARR',
  3631770 => 'UPC',
  3631771 => 'UPC',
  363178 => 'UPC',
  3631790 => 'UPC',
  36501 => 'DIGI',
  36502 => 'DIGI',
  36508 => 'MVM Net',
  36509 => 'MVM Net',
  3670 => 'One',
);
