<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  23020 => 'North Region',
  230210 => 'North Region',
  230211 => 'North Region',
  230212 => 'North Region',
  230213 => 'North Region',
  230214 => 'North Region',
  230215 => 'North Region',
  230216 => 'North Region',
  230217 => 'North Region',
  230218 => 'North Region',
  23023 => 'North Region',
  23024 => 'North Region',
  23026 => 'North Region',
  23027 => 'North Region',
  23028 => 'North Region',
  2304 => 'Central Region',
  2306 => 'South Region',
  23081 => 'Agalega',
  23083 => 'Rodrigues',
);
